# Low Level APIs

## Introduction

In [39]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

### Example 1
print("### EXAMPLE 1")

a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b

print(a)
print(b)
print(total)

sess = tf.Session()

print(sess.run(total))
print(sess.run({'ab':(a, b), 'total':total}))

### Example 2
print("### EXAMPLE 2")

vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2)))

### Example 3
print("### EXAMPLE 3")

x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

print(sess.run(z, feed_dict={x: 3, y: 4.5}))
print(sess.run(z, feed_dict={x: [1, 3], y: [2, 4]}))

### Example 4
print("### EXAMPLE 4")

my_data = [[0, 1,],[2, 3,],[4, 5,],[6, 7,],]
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()

print(slices)
print(next_item)

while True:
  try:
    print(sess.run(next_item))
  except tf.errors.OutOfRangeError:
    break
    
print("With Initialization:")

r = tf.random_normal([10,3])
dataset = tf.data.Dataset.from_tensor_slices(r)
iterator = dataset.make_initializable_iterator()
next_row = iterator.get_next()

sess.run(iterator.initializer)
while True:
  try:
    print(sess.run(next_row))
  except tf.errors.OutOfRangeError:
    break

### EXAMPLE 1
Tensor("Const_62:0", shape=(), dtype=float32)
Tensor("Const_63:0", shape=(), dtype=float32)
Tensor("add_79:0", shape=(), dtype=float32)
7.0
{'total': 7.0, 'ab': (3.0, 4.0)}
### EXAMPLE 2
[0.87870765 0.98638844 0.46808589]
[0.3498702  0.55027807 0.28086233]
(array([1.1625127, 1.6531645, 1.027079 ], dtype=float32), array([2.1625128, 2.6531644, 2.027079 ], dtype=float32))
### EXAMPLE 3
7.5
[3. 7.]
### EXAMPLE 4
<TensorSliceDataset shapes: (2,), types: tf.int32>
Tensor("IteratorGetNext_10:0", shape=(2,), dtype=int32)
[0 1]
[2 3]
[4 5]
[6 7]
With Initialization:
[-0.79248106  0.84623706  1.4429829 ]
[-2.373306    1.6729252   0.28561988]
[-1.0721095  1.1212237 -1.0906748]
[ 0.80825305 -0.10589179 -2.2995076 ]
[-0.33511165 -0.7235734   0.6235391 ]
[-0.34491518 -0.7155613   1.2417661 ]
[ 1.2868618 -1.1418914  1.03366  ]
[ 1.9918251 -0.961269  -0.6490845]
[-0.6762584 -1.5122948 -0.5179822]
[-0.9192039 -0.6546962 -0.3822412]
